targets:
  $default:
    builders:
      artemis:
        options:
          fragments_glob: lib/fragments/**.graphql
          schema_mapping:
            - schema: lib/schema.graphql
              queries_glob: lib/{queries,mutations}/**.graphql
              output: 'lib/generated/graphql_api.dart'              
